# Generated by Django 3.1.12 on 2025-09-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparqlresult',
            name='predicate',
        ),
        migrations.AlterField(
            model_name='sparqlresult',
            name='object',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='sparqlresult',
            name='subject',
            field=models.CharField(max_length=500),
        ),
    ]
